# Codage du fichier :
# -------------------
# Une ligne commencant par un '#' est un commentaire non pris en compte
# les lignes vides ne sont pas prises en compte
#
# [wait, database]
# - wait: temps d'attente en secondes avant de charger les données dans la database
# - database : Type de la base de données (activeMQ ou indexElastic) 
#
# les autres lignes sont considérées comme des données à rattacher 
# à la section sous laquelle elles apparaissent
#

# Ajout des documents PERF3 du jeu de donnees: 1, 3, 5, 6 et 8
[0, indexElastic]
1,Un
3,Trois
5,Cinq
6,Six
8,Huit

# Ajout du document PERF3 au jeu de donnees: 2 apres un delai de 7s
[7, indexElastic]
2,Deux

# Ajout du document PERF3 au jeu de donnees: 7 apres un delai de 12s
[12, indexElastic]
7,Sept

# Ajout des documents PERC33 du jeu de donnees: 1 à 5
[0, activeMQ]
1,Un
2,Deux
3,Trois
4,Quatre rejete
5,Cinq

# Ajout des documents du jeu de donnees: 6, 7 et 8 apres un delai de 7s
[7, activeMQ]
6,Six
7,Sept integre apres 1 retry
8,Huit

[25, activeMQ]
10,Dix en erreur
